name: anthology_common
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  copy_with_extension: ^6.0.1
  get_it: ^8.0.3
  html: ^0.15.6
  http: ^1.5.0
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.5.4
  copy_with_extension_gen: ^6.0.1
  lints: ^5.0.0
  test: ^1.24.0
