name: anthology_ui
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  anthology_common:
    path: /home/mohsen/apps/Anthology/anthology_common
  collection: ^1.19.1
  flutter:
    sdk: flutter
  get_it: ^8.2.0
  html: ^0.15.6
  http: ^1.5.0
  page_transition: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

formatter:
  trailing_commas: preserve
